import { useState } from 'react'; import { useMutation, useQuery } from '@tanstack/react-query'; import { DataTable } from '../../shared/components/DataTable'; import { PageHeader } from '../../shared/components/PageHeader'; import { QueryState } from '../../shared/components/QueryState'; import { formatQuantity } from '../../shared/format'; import { w4Api } from './w4Api';
type Mode = 'put-away' | 'relocation' | 'take-down';
const meta = { 'put-away': { id: 'LOC-02', title: 'Đưa batch lên kệ', description: 'Gán các batch chưa có vị trí vào một vị trí hợp lệ.' }, relocation: { id: 'LOC-03', title: 'Đổi vị trí kệ', description: 'Chuyển batch từ vị trí nguồn kỳ vọng sang vị trí đích trong một transaction.' }, 'take-down': { id: 'LOC-04', title: 'Đưa batch xuống kệ', description: 'Bỏ gán vị trí và ghi sự kiện xuống kệ.' } } as const;
export function LocationMovementPage({ mode }: { mode: Mode }) {
  const [search, setSearch] = useState(''); const [sourceLocation, setSourceLocation] = useState(''); const [targetLocation, setTargetLocation] = useState(''); const [selected, setSelected] = useState<Record<number, string | null>>({});
  const query = useQuery({ queryKey: [meta[mode].id, search, sourceLocation], queryFn: ({ signal }) => mode === 'put-away' ? w4Api.putAwayWorklist(search, signal) : mode === 'relocation' ? w4Api.relocationWorklist(search, sourceLocation, signal) : w4Api.takeDownWorklist(search, sourceLocation, signal) });
  const mutation = useMutation({ mutationFn: () => { const batches = Object.entries(selected).map(([id, location]) => ({ batchId: Number(id), expectedLocationCode: location })); return mode === 'put-away' ? w4Api.putAway(targetLocation, batches) : mode === 'relocation' ? w4Api.relocate(targetLocation, batches) : w4Api.takeDown(batches); }, onSuccess: () => { setSelected({}); void query.refetch(); } });
  return <><PageHeader useCaseId={meta[mode].id} title={meta[mode].title} description={meta[mode].description} /><div className="filter-bar"><label><span>📷 Quét / tìm batch</span><input className="barcode-input" autoFocus value={search} onChange={(e) => setSearch(e.target.value)} /></label>{mode !== 'put-away' ? <label><span>Vị trí nguồn</span><input className="barcode-input" value={sourceLocation} onChange={(e) => setSourceLocation(e.target.value)} /></label> : null}{mode !== 'take-down' ? <label><span>Vị trí đích</span><select value={targetLocation} onChange={(e) => setTargetLocation(e.target.value)}><option value="">Chọn vị trí</option>{query.data?.locations.map((l) => <option key={l.locationCode} value={l.locationCode}>{l.locationCode} · {l.description}</option>)}</select></label> : null}</div>
    <QueryState isLoading={query.isLoading} error={query.error} isEmpty={query.data?.items.length === 0} onRetry={() => void query.refetch()}><DataTable caption={meta[mode].title} rows={query.data?.items ?? []} rowKey={(x) => String(x.batchId)} columns={[
      { key: 'select', header: 'Chọn', render: (x) => <input aria-label={`Chọn batch ${x.batchId}`} type="checkbox" checked={Object.hasOwn(selected, x.batchId)} onChange={(e) => setSelected((c) => e.target.checked ? { ...c, [x.batchId]: x.locationCode } : Object.fromEntries(Object.entries(c).filter(([key]) => key !== String(x.batchId))))} /> }, { key: 'batch', header: 'Batch', render: (x) => `#${x.batchId}` }, { key: 'material', header: 'Vật tư', render: (x) => `${x.materialId ?? '—'} · ${x.materialName ?? ''}` }, { key: 'qty', header: 'Số lượng', align: 'right', render: (x) => `${formatQuantity(x.quantity)} ${x.unit ?? ''}` }, { key: 'location', header: 'Vị trí hiện tại', render: (x) => x.locationCode ? <span className="location-badge">{x.locationCode}</span> : 'Chưa lên kệ' },
    ]} /></QueryState><section className="form-card"><div className="form-actions"><strong>{Object.keys(selected).length} batch đã chọn</strong><button className="button primary" type="button" disabled={!Object.keys(selected).length || (mode !== 'take-down' && !targetLocation) || mutation.isPending} onClick={() => mutation.mutate()}>Xác nhận</button></div>{mutation.isSuccess ? <p className="action-success">Đã cập nhật {mutation.data.batchCount} batch.</p> : null}{mutation.error ? <p className="action-error">{mutation.error.message}</p> : null}</section></>;
}
