import { useState } from 'react'; import { useMutation, useQuery } from '@tanstack/react-query'; import { DataTable } from '../../shared/components/DataTable'; import { PageHeader } from '../../shared/components/PageHeader'; import { QueryState } from '../../shared/components/QueryState'; import { formatQuantity } from '../../shared/format'; import { w4Api } from './w4Api';
export function LocationCountPage() {
  const [locationText, setLocationText] = useState(''); const [location, setLocation] = useState<string | null>(null); const [actual, setActual] = useState<Record<number, string>>({}); const [reason, setReason] = useState(''); const [selected, setSelected] = useState<number | null>(null);
  const query = useQuery({ queryKey: ['INV-07', location], queryFn: ({ signal }) => w4Api.locationCount(location ?? '', signal), enabled: location !== null });
  const batch = query.data?.batches.find((x) => x.batchId === selected);
  const mutation = useMutation({ mutationFn: () => w4Api.countLocationBatch(location ?? '', selected ?? 0, Number(actual[selected ?? 0]), batch?.systemQuantity ?? 0, reason), onSuccess: () => void query.refetch() });
  return <><PageHeader useCaseId="INV-07" title="Kiểm kê theo vị trí" description="Tải toàn bộ batch tại vị trí, đối chiếu từng batch và khóa vị trí kỳ vọng khi ghi." /><div className="filter-bar"><label><span>Mã vị trí</span><input value={locationText} onChange={(e) => setLocationText(e.target.value)} /></label><button className="button secondary" type="button" disabled={!locationText.trim()} onClick={() => { setLocation(locationText.trim()); setSelected(null); }}>Tải vị trí</button></div>{location ? <QueryState isLoading={query.isLoading} error={query.error} isEmpty={!query.data?.location} onRetry={() => void query.refetch()}>{query.data?.location ? <section className="form-card"><h2>{query.data.location.locationCode} · {query.data.location.description ?? ''}</h2><label><span>Căn cứ đợt kiểm kê</span><input maxLength={50} value={reason} onChange={(e) => setReason(e.target.value)} /></label><DataTable caption="Batch tại vị trí" rows={query.data.batches} rowKey={(x) => String(x.batchId)} columns={[
      { key: 'batch', header: 'Batch', render: (x) => <button className="link-button" type="button" onClick={() => { setSelected(x.batchId); setActual((c) => ({ ...c, [x.batchId]: String(x.systemQuantity) })); }}>#{x.batchId}</button> }, { key: 'material', header: 'Vật tư', render: (x) => `${x.materialId ?? '—'} · ${x.materialName ?? ''}` }, { key: 'system', header: 'Hệ thống', align: 'right', render: (x) => `${formatQuantity(x.systemQuantity)} ${x.unit ?? ''}` }, { key: 'actual', header: 'Thực tế', render: (x) => <input type="number" min="0" step="any" disabled={selected !== x.batchId} value={actual[x.batchId] ?? ''} onChange={(e) => setActual((c) => ({ ...c, [x.batchId]: e.target.value }))} /> },
    ]} /><button className="button primary" type="button" disabled={!selected || actual[selected] === '' || !reason.trim() || mutation.isPending} onClick={() => mutation.mutate()}>Ghi kết quả batch</button>{mutation.isSuccess ? <p className="action-success">Đã ghi batch #{mutation.data.batchId}; chênh lệch {formatQuantity(mutation.data.differenceQuantity)}.</p> : null}{mutation.error ? <p className="action-error">{mutation.error.message}</p> : null}</section> : null}</QueryState> : <div className="state-panel">Quét hoặc nhập vị trí để bắt đầu.</div>}</>;
}

