import { useState } from 'react'; import { useMutation, useQuery } from '@tanstack/react-query'; import { DataTable } from '../../shared/components/DataTable'; import { PageHeader } from '../../shared/components/PageHeader'; import { QueryState } from '../../shared/components/QueryState'; import { formatQuantity } from '../../shared/format'; import { w4Api } from './w4Api';
export function SplitBatchPage() {
  const [search, setSearch] = useState(''); const [selected, setSelected] = useState<{ batchId: number; quantity: number } | null>(null); const [split, setSplit] = useState('');
  const query = useQuery({ queryKey: ['INV-05', search], queryFn: ({ signal }) => w4Api.splittableBatches(search, null, signal) });
  const mutation = useMutation({ mutationFn: () => w4Api.splitBatch(selected?.batchId ?? 0, Number(split), selected?.quantity ?? 0), onSuccess: () => void query.refetch() });
  return <><PageHeader useCaseId="INV-05" title="Tách batch" description="Tách một phần tồn sang batch mới, kiểm tra cân bằng transaction trước khi commit." /><div className="filter-bar"><label><span>Tìm batch</span><input value={search} onChange={(e) => setSearch(e.target.value)} /></label></div>
    <QueryState isLoading={query.isLoading} error={query.error} isEmpty={query.data?.items.length === 0} onRetry={() => void query.refetch()}><DataTable caption="Batch có thể tách" rows={query.data?.items ?? []} rowKey={(x) => String(x.batchId)} columns={[
      { key: 'batch', header: 'Batch', render: (x) => <button className="link-button" type="button" disabled={!x.isBalanced} onClick={() => { setSelected({ batchId: x.batchId, quantity: x.quantity }); setSplit(''); }}>#{x.batchId}</button> }, { key: 'material', header: 'Vật tư', render: (x) => `${x.materialId ?? '—'} · ${x.materialName ?? ''}` }, { key: 'quantity', header: 'Tồn', align: 'right', render: (x) => `${formatQuantity(x.quantity)} ${x.unit ?? ''}` }, { key: 'balance', header: 'Đối chiếu', render: (x) => <span className={x.isBalanced ? 'text-success' : 'text-danger'}>{x.isBalanced ? 'Cân bằng' : 'Lệch transaction'}</span> },
    ]} /></QueryState>{selected ? <section className="form-card"><h2>Tách batch #{selected.batchId}</h2><label><span>Số lượng tách (nhỏ hơn {formatQuantity(selected.quantity)})</span><input type="number" min="0" max={selected.quantity} step="any" value={split} onChange={(e) => setSplit(e.target.value)} /></label><button className="button primary" type="button" disabled={mutation.isPending || Number(split) <= 0 || Number(split) >= selected.quantity} onClick={() => mutation.mutate()}>Tạo batch mới</button>{mutation.isSuccess ? <p className="action-success">Batch mới #{mutation.data.newBatchId}, số lượng {formatQuantity(mutation.data.newQuantity)}.</p> : null}{mutation.error ? <p className="action-error">{mutation.error.message}</p> : null}</section> : null}</>;
}

