import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { DataTable } from '../../shared/components/DataTable';
import { PageHeader } from '../../shared/components/PageHeader';
import { QueryState } from '../../shared/components/QueryState';
import { formatDateTime, formatQuantity } from '../../shared/format';
import { w7Api } from './w7Api';

export function ConfirmInternalReturnPage() {
  const queryClient = useQueryClient(); const [search, setSearch] = useState(''); const [returnId, setReturnId] = useState(0);
  const [result, setResult] = useState(1); const [note, setNote] = useState(''); const [bravo, setBravo] = useState('');
  const queue = useQuery({ queryKey: ['RET-02', search], queryFn: ({ signal }) => w7Api.queue(search, '1', signal) });
  const detail = useQuery({ queryKey: ['RET-02-detail', returnId], queryFn: ({ signal }) => w7Api.detail(returnId, signal), enabled: returnId > 0 });
  const confirm = useMutation({ mutationFn: () => w7Api.confirm(returnId, result, note, bravo), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['RET-02'] }); await queryClient.invalidateQueries({ queryKey: ['RET-02-detail', returnId] }); } });
  return <><PageHeader useCaseId="RET-02" title="Kho xác nhận trả nội bộ" description="Giữ nguyên ba kết quả: nhập đạt, nhập không đạt, từ chối. Batch và transaction được tạo set-based trong một giao dịch." />
    <section className="filter-bar"><label><span>Tìm phiếu chờ kho</span><input value={search} onChange={(event) => setSearch(event.target.value)} /></label></section>
    <QueryState isLoading={queue.isLoading} error={queue.error} isEmpty={queue.data?.items.length === 0} onRetry={() => void queue.refetch()}><DataTable caption="Phiếu chờ xử lý" rows={queue.data?.items ?? []} rowKey={(item) => String(item.returnId)} columns={[{ key: 'id', header: 'Phiếu', render: (item) => `#${item.returnId}` }, { key: 'destination', header: 'Đơn vị trả', render: (item) => item.destinationName ?? item.destinationBravoCode ?? '—' }, { key: 'date', header: 'Ngày trả', render: (item) => formatDateTime(item.returnAt) }, { key: 'quantity', header: 'Tổng SL', align: 'right', render: (item) => formatQuantity(item.totalQuantity) }, { key: 'open', header: '', render: (item) => <button type="button" className="button secondary" onClick={() => { setReturnId(item.returnId); setNote(''); }}>Mở</button> }]} /></QueryState>
    {returnId > 0 ? <QueryState isLoading={detail.isLoading} error={detail.error} isEmpty={!detail.data} onRetry={() => void detail.refetch()}>{detail.data ? <section className="form-card"><h2>Phiếu #{returnId} · {detail.data.header.destinationName}</h2><DataTable caption="Chi tiết vật tư trả" rows={detail.data.lines} rowKey={(line) => String(line.lineId)} columns={[{ key: 'material', header: 'Vật tư', render: (line) => `${line.materialId ?? ''} · ${line.materialName ?? ''}` }, { key: 'quantity', header: 'Số lượng', align: 'right', render: (line) => `${formatQuantity(line.quantity)} ${line.unit ?? ''}` }, { key: 'note', header: 'Lý do trả', render: (line) => line.note ?? '—' }]} />
      <div className="form-grid three-columns"><label><span>Kết quả kho</span><select value={result} onChange={(event) => setResult(Number(event.target.value))}><option value={1}>1 · Nhập kho đạt chất lượng</option><option value={2}>2 · Nhập kho không đạt chất lượng</option><option value={3}>3 · Từ chối nhập kho</option></select></label><label><span>Số chứng từ Bravo</span><input value={bravo} onChange={(event) => setBravo(event.target.value)} /></label><label><span>Ghi chú / lý do từ chối</span><input value={note} onChange={(event) => setNote(event.target.value)} /></label></div><button className="button primary" type="button" disabled={!detail.data.header.canConfirm || (result === 3 && !note.trim()) || confirm.isPending} onClick={() => confirm.mutate()}>Xác nhận kết quả</button>{confirm.data ? <p className="action-success">Đã xử lý phiếu; tạo {confirm.data.createdBatchCount} batch.</p> : null}{confirm.error ? <p className="action-error">{confirm.error.message}</p> : null}</section> : null}</QueryState> : null}</>;
}
