import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { DataTable } from '../../shared/components/DataTable';
import { PageHeader } from '../../shared/components/PageHeader';
import { QueryState } from '../../shared/components/QueryState';
import { formatDateTime, formatQuantity } from '../../shared/format';
import type { ReturnBatch } from './contracts';
import { w7Api } from './w7Api';

export function SplitReturnBatchPage() {
  const queryClient = useQueryClient(); const [search, setSearch] = useState(''); const [documentId, setDocumentId] = useState(0);
  const [batch, setBatch] = useState<ReturnBatch | null>(null); const [quantity, setQuantity] = useState('');
  const documents = useQuery({ queryKey: ['RET-03-documents', search], queryFn: ({ signal }) => w7Api.documents(search, signal) });
  const batches = useQuery({ queryKey: ['RET-03-batches', documentId], queryFn: ({ signal }) => w7Api.batches(documentId, signal), enabled: documentId > 0 });
  const split = useMutation({ mutationFn: () => { if (!batch) throw new Error('Vui lòng chọn batch.'); return w7Api.split(documentId, batch.batchId, Number(quantity), batch.quantity); }, onSuccess: async () => { setBatch(null); setQuantity(''); await queryClient.invalidateQueries({ queryKey: ['RET-03-batches', documentId] }); await queryClient.invalidateQueries({ queryKey: ['RET-03-documents'] }); } });
  return <><PageHeader useCaseId="RET-03" title="Tách batch nhập trả" description="Tách trên đúng chứng từ IN_PROD, khóa batch và kiểm tra cân bằng transaction trước khi tạo batch mới." />
    <section className="filter-bar"><label><span>Tìm chứng từ</span><input value={search} onChange={(event) => setSearch(event.target.value)} /></label></section>
    <QueryState isLoading={documents.isLoading} error={documents.error} isEmpty={documents.data?.length === 0} onRetry={() => void documents.refetch()}><DataTable caption="Chứng từ nhập trả" rows={documents.data ?? []} rowKey={(item) => String(item.transactionDocumentId)} columns={[{ key: 'document', header: 'Chứng từ', render: (item) => `#${item.transactionDocumentId}` }, { key: 'return', header: 'Phiếu trả', render: (item) => item.returnId ? `#${item.returnId}` : 'Legacy' }, { key: 'destination', header: 'Đơn vị', render: (item) => item.destinationName ?? item.destinationCode ?? '—' }, { key: 'time', header: 'Thời gian', render: (item) => formatDateTime(item.createdAt) }, { key: 'quantity', header: 'Tổng SL', align: 'right', render: (item) => formatQuantity(item.totalQuantity) }, { key: 'open', header: '', render: (item) => <button type="button" className="button secondary" onClick={() => { setDocumentId(item.transactionDocumentId); setBatch(null); }}>Mở</button> }]} /></QueryState>
    {documentId > 0 ? <section className="form-card"><h2>Batch của chứng từ #{documentId}</h2><QueryState isLoading={batches.isLoading} error={batches.error} isEmpty={batches.data?.length === 0} onRetry={() => void batches.refetch()}><DataTable caption="Batch nhập trả" rows={batches.data ?? []} rowKey={(item) => String(item.batchId)} columns={[{ key: 'batch', header: 'Batch', render: (item) => `#${item.batchId}` }, { key: 'material', header: 'Vật tư', render: (item) => `${item.materialId ?? ''} · ${item.materialName ?? ''}` }, { key: 'quantity', header: 'Tồn', align: 'right', render: (item) => `${formatQuantity(item.quantity)} ${item.unit ?? ''}` }, { key: 'status', header: 'TT tồn', render: (item) => item.inventoryStatusCode ?? '—' }, { key: 'select', header: '', render: (item) => <button type="button" className="button secondary" onClick={() => { setBatch(item); setQuantity(''); }}>Chọn</button> }]} /></QueryState>
      {batch ? <div className="form-actions"><label><span>Tách từ batch #{batch.batchId} · tồn {formatQuantity(batch.quantity)}</span><input type="number" min="0" step="0.0001" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><button type="button" className="button primary" disabled={Number(quantity) <= 0 || Number(quantity) >= batch.quantity || split.isPending} onClick={() => split.mutate()}>Tách batch</button></div> : null}{split.data ? <p className="action-success">Đã tạo batch mới #{split.data.newBatchId}.</p> : null}{split.error ? <p className="action-error">{split.error.message}</p> : null}</section> : null}</>;
}
